### PR TITLE
McJty Mods 1.8+ Compatibility

### PR DESCRIPTION
**Pull request by stefancdr**
This PR attempts to add McJty Mods 1.8+ compatibility, as McJty had to do so some backwards compatibility breaking changes to his mods to prepare for 1.13 and 1.14. Specifically, using YNot 0.2.3 with XNet 1.8+ results in a crash when gas-using machines are ticked due to a ClassDefNotFoundException. This PR'd version uses the newer classes in 1.8+ and seems to be working.

What I did to develop this PR:

1. Forked this repo.
2. Copied over the build.gradle and src folder of Ynot 0.2.3.
3. Made required changes to be compatible with Xnet 1.8+.

Thanks for reviewing.

### CODE REVIEW

**Comment by asiekierka** [comment]
Could you please rebase? I've pushed the 0.2.3 code from my Git over to GitHub, to try and keep continuity.

**Comment by stefancdr** [comment]
I... tried. Hopefully this meets the specifications. If not, I'll delete this PR, delete my fork and try from a fresh fork, because rewriting history in Git like this is harder than I'd like.

**Comment by asiekierka** [comment]
Found some time today; I'll just do it myself, and also update the Mekanism dependency. Sorry! But thanks for making me aware of the breakage, either way.

**Comment by asiekierka** [comment]
Done and updated. Should be live in 1-2 minutes from now.

**Pull request closed without merging**
